language: node_js
node_js:
  - "6.2.0"
branches:
  only:
    - master
before_script:
  - npm install -g mocha
  - npm install -g jshint
  - npm install

script:
  - jshint ./lib/cli.js ./bin/ngdeploy ./test/*.js
  - npm test