language: node_js
node_js:
  - "6.2.0"
branches:
  only:
    - master
before_script:
  - npm install -g mocha
  - npm install -g jscs
  - npm install

script:
  - jscs ./lib/cli.js
  - jscs ./bin/ngdeploy
  - npm test